import { useEffect, useState } from "react";
import { api } from "../api/client";

type PatientSummary = {
  id: number;
  name?: string;
  dosha?: string;
  lastAiDisease?: string;
  age?: number;
};

export default function ReportPage() {
  const [patient, setPatient] = useState<PatientSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [msg, setMsg] = useState<{ text: string; type: "success" | "error" } | null>(null);

  useEffect(() => {
    api
      .get<PatientSummary>("/patients/me")
      .then((r) => setPatient(r.data))
      .catch((e) => {
        const ax = e as { response?: { data?: { message?: string } }; message?: string };
        setMsg({ text: ax.response?.data?.message ?? ax.message ?? "Failed to load profile", type: "error" });
      })
      .finally(() => setLoading(false));
  }, []);

  async function download() {
    if (!patient) return;
    setMsg(null);
    setDownloading(true);
    try {
      const res = await api.get(`/generate-report/${patient.id}`, { responseType: "blob" });
      const url = window.URL.createObjectURL(res.data as Blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `aryogasutra-report-${patient.id}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      setMsg({ text: "Report downloaded successfully.", type: "success" });
    } catch (e) {
      const ax = e as { response?: { data?: { message?: string } }; message?: string };
      setMsg({ text: ax.response?.data?.message ?? ax.message ?? "Download failed", type: "error" });
    } finally {
      setDownloading(false);
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[40vh]">
        <div className="w-8 h-8 border-4 border-ayur-moss border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-md mx-auto space-y-4">
      <div>
        <h2 className="text-xl font-semibold text-ayur-leaf">PDF Health Report</h2>
        <p className="text-sm text-stone-500 mt-1">
          Generated by the Java backend using iText — includes your full health summary.
        </p>
      </div>

      {/* Feedback */}
      {msg && (
        <div
          className={`rounded-lg px-3 py-2 text-sm border ${
            msg.type === "success"
              ? "bg-green-50 border-green-200 text-green-700"
              : "bg-red-50 border-red-200 text-red-700"
          }`}
        >
          {msg.text}
        </div>
      )}

      {/* Patient summary preview */}
      {patient && (
        <div className="bg-white rounded-2xl border border-stone-200 p-5 space-y-3">
          <h3 className="font-semibold text-stone-700">Report will include:</h3>
          <div className="space-y-2 text-sm">
            <div className="flex items-center gap-3">
              <span className="text-xl">👤</span>
              <div>
                <p className="text-stone-500 text-xs">Patient</p>
                <p className="font-medium text-stone-800">{patient.name ?? "—"}</p>
              </div>
            </div>
            {patient.age && (
              <div className="flex items-center gap-3">
                <span className="text-xl">🎂</span>
                <div>
                  <p className="text-stone-500 text-xs">Age</p>
                  <p className="font-medium text-stone-800">{patient.age}</p>
                </div>
              </div>
            )}
            {patient.dosha && (
              <div className="flex items-center gap-3">
                <span className="text-xl">🌿</span>
                <div>
                  <p className="text-stone-500 text-xs">Dosha</p>
                  <p className="font-medium text-stone-800">{patient.dosha}</p>
                </div>
              </div>
            )}
            {patient.lastAiDisease && (
              <div className="flex items-center gap-3">
                <span className="text-xl">🔬</span>
                <div>
                  <p className="text-stone-500 text-xs">Last AI prediction</p>
                  <p className="font-medium text-stone-800">{patient.lastAiDisease}</p>
                </div>
              </div>
            )}
          </div>

          <div className="border-t border-stone-100 pt-3 space-y-1 text-xs text-stone-400">
            <p>✅ Dosha questionnaire results</p>
            <p>✅ AI prediction snapshot</p>
            <p>✅ Doctor treatment suggestions</p>
          </div>
        </div>
      )}

      <button
        type="button"
        disabled={!patient || downloading}
        onClick={download}
        className="w-full py-3 rounded-xl bg-ayur-moss text-white font-semibold hover:bg-ayur-leaf transition disabled:opacity-60 flex items-center justify-center gap-2"
      >
        {downloading && (
          <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
        )}
        {downloading ? "Generating PDF…" : "⬇ Download PDF Report"}
      </button>

      <p className="text-xs text-stone-400 text-center">
        ⚠️ For informational purposes only — not a medical record.
      </p>
    </div>
  );
}
